#ifndef DYNAMICS_MODEL_H
#define DYNAMICS_MODEL_H

// Mass Matrix
void calculate_M_0_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_6(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_7(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_0_8(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_6(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_7(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_1_8(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_2_6(double *val);
void calculate_M_2_7(double *val);
void calculate_M_2_8(double *val);
void calculate_M_3_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_6(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_7(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_3_8(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_6(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_7(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_4_8(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_2(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_6(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_7(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_5_8(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_2(double *val);
void calculate_M_6_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_6(const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_7(const double sbo[3], const double cbo[3], double *val);
void calculate_M_6_8(const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_2(double *val);
void calculate_M_7_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_6(const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_7(const double sbo[3], const double cbo[3], double *val);
void calculate_M_7_8(const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_2(double *val);
void calculate_M_8_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_6(const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_7(const double sbo[3], const double cbo[3], double *val);
void calculate_M_8_8(const double sbo[3], const double cbo[3], double *val);

// Coriolis Matrix
void calculate_C_0_0(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_1(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_6(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_7(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_0_8(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_0(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_1(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_6(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_7(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_1_8(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_0(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_1(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_3(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_4(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_5(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_2_6(double *val);
void calculate_C_2_7(double *val);
void calculate_C_2_8(double *val);
void calculate_C_3_0(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_1(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_3(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_6(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_7(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_3_8(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_0(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_1(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_4(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_6(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_7(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_4_8(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_0(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_1(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_2(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_5(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_6(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_7(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_5_8(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_0(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_1(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_2(double *val);
void calculate_C_6_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_6(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_7(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_6_8(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_0(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_1(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_2(double *val);
void calculate_C_7_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_6(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_7(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_7_8(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_0(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_1(const double dq[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_2(double *val);
void calculate_C_8_3(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_4(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_5(const double dq[3], const double base_vel[3], const double base_dori[3], const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_6(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_7(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);
void calculate_C_8_8(const double base_dori[3], const double sbo[3], const double cbo[3], double *val);

// Gravity Vector
void calculate_G_0(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_G_1(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_G_2(double *val);
void calculate_G_3(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_G_4(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_G_5(const double sq[3], const double cq[3], const double sbo[3], const double cbo[3], double *val);
void calculate_G_6(double *val);
void calculate_G_7(double *val);
void calculate_G_8(double *val);

void compute_dynamics(const double q[3], const double dq[3], const double ddq[3],
    const double base_pos[3], const double base_vel[3], const double base_acc[3],
    const double base_ori[3], const double base_dori[3], const double base_ddori[3],
    double M[9][9], double C[9][9], double G[9], double tau[9]);

#endif
