#include "model.h"
#include "params.h"

extern void calculate_G_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_0_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_0_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_1_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_1_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_2_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_2_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_3_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_3_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_4_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_4_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_5_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_5_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_6_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_6_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_7_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_7_8(const double q[9], const double dq[9], double *val);
extern void calculate_G_8(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_0(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_0(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_1(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_1(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_2(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_2(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_3(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_3(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_4(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_4(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_5(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_5(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_6(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_6(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_7(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_7(const double q[9], const double dq[9], double *val);
extern void calculate_M_8_8(const double q[9], const double dq[9], double *val);
extern void calculate_C_8_8(const double q[9], const double dq[9], double *val);

void compute_dynamics(const double q_meas[3], const double q_dot_meas[3], const double q_acc_meas[3], const double b_pos[3], const double b_vel[3], const double b_acc[3], const double b_ori[3], const double b_dori[3], const double b_ddori[3], double M[9][9], double C[9][9], double G[9], double tau[9]) {
  double q_full[9], dq_full[9];
  q_full[0] = q_meas[0]; dq_full[0] = q_dot_meas[0];
  q_full[3] = b_ori[0]; dq_full[3] = b_dori[0];
  q_full[6] = b_pos[0]; dq_full[6] = b_vel[0];
  q_full[1] = q_meas[1]; dq_full[1] = q_dot_meas[1];
  q_full[4] = b_ori[1]; dq_full[4] = b_dori[1];
  q_full[7] = b_pos[1]; dq_full[7] = b_vel[1];
  q_full[2] = q_meas[2]; dq_full[2] = q_dot_meas[2];
  q_full[5] = b_ori[2]; dq_full[5] = b_dori[2];
  q_full[8] = b_pos[2]; dq_full[8] = b_vel[2];
  calculate_G_0(q_full, dq_full, &G[0]);
  calculate_M_0_0(q_full, dq_full, &M[0][0]);
  calculate_C_0_0(q_full, dq_full, &C[0][0]);
  calculate_M_0_1(q_full, dq_full, &M[0][1]);
  calculate_C_0_1(q_full, dq_full, &C[0][1]);
  calculate_M_0_2(q_full, dq_full, &M[0][2]);
  calculate_C_0_2(q_full, dq_full, &C[0][2]);
  calculate_M_0_3(q_full, dq_full, &M[0][3]);
  calculate_C_0_3(q_full, dq_full, &C[0][3]);
  calculate_M_0_4(q_full, dq_full, &M[0][4]);
  calculate_C_0_4(q_full, dq_full, &C[0][4]);
  calculate_M_0_5(q_full, dq_full, &M[0][5]);
  calculate_C_0_5(q_full, dq_full, &C[0][5]);
  calculate_M_0_6(q_full, dq_full, &M[0][6]);
  calculate_C_0_6(q_full, dq_full, &C[0][6]);
  calculate_M_0_7(q_full, dq_full, &M[0][7]);
  calculate_C_0_7(q_full, dq_full, &C[0][7]);
  calculate_M_0_8(q_full, dq_full, &M[0][8]);
  calculate_C_0_8(q_full, dq_full, &C[0][8]);
  calculate_G_1(q_full, dq_full, &G[1]);
  calculate_M_1_0(q_full, dq_full, &M[1][0]);
  calculate_C_1_0(q_full, dq_full, &C[1][0]);
  calculate_M_1_1(q_full, dq_full, &M[1][1]);
  calculate_C_1_1(q_full, dq_full, &C[1][1]);
  calculate_M_1_2(q_full, dq_full, &M[1][2]);
  calculate_C_1_2(q_full, dq_full, &C[1][2]);
  calculate_M_1_3(q_full, dq_full, &M[1][3]);
  calculate_C_1_3(q_full, dq_full, &C[1][3]);
  calculate_M_1_4(q_full, dq_full, &M[1][4]);
  calculate_C_1_4(q_full, dq_full, &C[1][4]);
  calculate_M_1_5(q_full, dq_full, &M[1][5]);
  calculate_C_1_5(q_full, dq_full, &C[1][5]);
  calculate_M_1_6(q_full, dq_full, &M[1][6]);
  calculate_C_1_6(q_full, dq_full, &C[1][6]);
  calculate_M_1_7(q_full, dq_full, &M[1][7]);
  calculate_C_1_7(q_full, dq_full, &C[1][7]);
  calculate_M_1_8(q_full, dq_full, &M[1][8]);
  calculate_C_1_8(q_full, dq_full, &C[1][8]);
  calculate_G_2(q_full, dq_full, &G[2]);
  calculate_M_2_0(q_full, dq_full, &M[2][0]);
  calculate_C_2_0(q_full, dq_full, &C[2][0]);
  calculate_M_2_1(q_full, dq_full, &M[2][1]);
  calculate_C_2_1(q_full, dq_full, &C[2][1]);
  calculate_M_2_2(q_full, dq_full, &M[2][2]);
  calculate_C_2_2(q_full, dq_full, &C[2][2]);
  calculate_M_2_3(q_full, dq_full, &M[2][3]);
  calculate_C_2_3(q_full, dq_full, &C[2][3]);
  calculate_M_2_4(q_full, dq_full, &M[2][4]);
  calculate_C_2_4(q_full, dq_full, &C[2][4]);
  calculate_M_2_5(q_full, dq_full, &M[2][5]);
  calculate_C_2_5(q_full, dq_full, &C[2][5]);
  calculate_M_2_6(q_full, dq_full, &M[2][6]);
  calculate_C_2_6(q_full, dq_full, &C[2][6]);
  calculate_M_2_7(q_full, dq_full, &M[2][7]);
  calculate_C_2_7(q_full, dq_full, &C[2][7]);
  calculate_M_2_8(q_full, dq_full, &M[2][8]);
  calculate_C_2_8(q_full, dq_full, &C[2][8]);
  calculate_G_3(q_full, dq_full, &G[3]);
  calculate_M_3_0(q_full, dq_full, &M[3][0]);
  calculate_C_3_0(q_full, dq_full, &C[3][0]);
  calculate_M_3_1(q_full, dq_full, &M[3][1]);
  calculate_C_3_1(q_full, dq_full, &C[3][1]);
  calculate_M_3_2(q_full, dq_full, &M[3][2]);
  calculate_C_3_2(q_full, dq_full, &C[3][2]);
  calculate_M_3_3(q_full, dq_full, &M[3][3]);
  calculate_C_3_3(q_full, dq_full, &C[3][3]);
  calculate_M_3_4(q_full, dq_full, &M[3][4]);
  calculate_C_3_4(q_full, dq_full, &C[3][4]);
  calculate_M_3_5(q_full, dq_full, &M[3][5]);
  calculate_C_3_5(q_full, dq_full, &C[3][5]);
  calculate_M_3_6(q_full, dq_full, &M[3][6]);
  calculate_C_3_6(q_full, dq_full, &C[3][6]);
  calculate_M_3_7(q_full, dq_full, &M[3][7]);
  calculate_C_3_7(q_full, dq_full, &C[3][7]);
  calculate_M_3_8(q_full, dq_full, &M[3][8]);
  calculate_C_3_8(q_full, dq_full, &C[3][8]);
  calculate_G_4(q_full, dq_full, &G[4]);
  calculate_M_4_0(q_full, dq_full, &M[4][0]);
  calculate_C_4_0(q_full, dq_full, &C[4][0]);
  calculate_M_4_1(q_full, dq_full, &M[4][1]);
  calculate_C_4_1(q_full, dq_full, &C[4][1]);
  calculate_M_4_2(q_full, dq_full, &M[4][2]);
  calculate_C_4_2(q_full, dq_full, &C[4][2]);
  calculate_M_4_3(q_full, dq_full, &M[4][3]);
  calculate_C_4_3(q_full, dq_full, &C[4][3]);
  calculate_M_4_4(q_full, dq_full, &M[4][4]);
  calculate_C_4_4(q_full, dq_full, &C[4][4]);
  calculate_M_4_5(q_full, dq_full, &M[4][5]);
  calculate_C_4_5(q_full, dq_full, &C[4][5]);
  calculate_M_4_6(q_full, dq_full, &M[4][6]);
  calculate_C_4_6(q_full, dq_full, &C[4][6]);
  calculate_M_4_7(q_full, dq_full, &M[4][7]);
  calculate_C_4_7(q_full, dq_full, &C[4][7]);
  calculate_M_4_8(q_full, dq_full, &M[4][8]);
  calculate_C_4_8(q_full, dq_full, &C[4][8]);
  calculate_G_5(q_full, dq_full, &G[5]);
  calculate_M_5_0(q_full, dq_full, &M[5][0]);
  calculate_C_5_0(q_full, dq_full, &C[5][0]);
  calculate_M_5_1(q_full, dq_full, &M[5][1]);
  calculate_C_5_1(q_full, dq_full, &C[5][1]);
  calculate_M_5_2(q_full, dq_full, &M[5][2]);
  calculate_C_5_2(q_full, dq_full, &C[5][2]);
  calculate_M_5_3(q_full, dq_full, &M[5][3]);
  calculate_C_5_3(q_full, dq_full, &C[5][3]);
  calculate_M_5_4(q_full, dq_full, &M[5][4]);
  calculate_C_5_4(q_full, dq_full, &C[5][4]);
  calculate_M_5_5(q_full, dq_full, &M[5][5]);
  calculate_C_5_5(q_full, dq_full, &C[5][5]);
  calculate_M_5_6(q_full, dq_full, &M[5][6]);
  calculate_C_5_6(q_full, dq_full, &C[5][6]);
  calculate_M_5_7(q_full, dq_full, &M[5][7]);
  calculate_C_5_7(q_full, dq_full, &C[5][7]);
  calculate_M_5_8(q_full, dq_full, &M[5][8]);
  calculate_C_5_8(q_full, dq_full, &C[5][8]);
  calculate_G_6(q_full, dq_full, &G[6]);
  calculate_M_6_0(q_full, dq_full, &M[6][0]);
  calculate_C_6_0(q_full, dq_full, &C[6][0]);
  calculate_M_6_1(q_full, dq_full, &M[6][1]);
  calculate_C_6_1(q_full, dq_full, &C[6][1]);
  calculate_M_6_2(q_full, dq_full, &M[6][2]);
  calculate_C_6_2(q_full, dq_full, &C[6][2]);
  calculate_M_6_3(q_full, dq_full, &M[6][3]);
  calculate_C_6_3(q_full, dq_full, &C[6][3]);
  calculate_M_6_4(q_full, dq_full, &M[6][4]);
  calculate_C_6_4(q_full, dq_full, &C[6][4]);
  calculate_M_6_5(q_full, dq_full, &M[6][5]);
  calculate_C_6_5(q_full, dq_full, &C[6][5]);
  calculate_M_6_6(q_full, dq_full, &M[6][6]);
  calculate_C_6_6(q_full, dq_full, &C[6][6]);
  calculate_M_6_7(q_full, dq_full, &M[6][7]);
  calculate_C_6_7(q_full, dq_full, &C[6][7]);
  calculate_M_6_8(q_full, dq_full, &M[6][8]);
  calculate_C_6_8(q_full, dq_full, &C[6][8]);
  calculate_G_7(q_full, dq_full, &G[7]);
  calculate_M_7_0(q_full, dq_full, &M[7][0]);
  calculate_C_7_0(q_full, dq_full, &C[7][0]);
  calculate_M_7_1(q_full, dq_full, &M[7][1]);
  calculate_C_7_1(q_full, dq_full, &C[7][1]);
  calculate_M_7_2(q_full, dq_full, &M[7][2]);
  calculate_C_7_2(q_full, dq_full, &C[7][2]);
  calculate_M_7_3(q_full, dq_full, &M[7][3]);
  calculate_C_7_3(q_full, dq_full, &C[7][3]);
  calculate_M_7_4(q_full, dq_full, &M[7][4]);
  calculate_C_7_4(q_full, dq_full, &C[7][4]);
  calculate_M_7_5(q_full, dq_full, &M[7][5]);
  calculate_C_7_5(q_full, dq_full, &C[7][5]);
  calculate_M_7_6(q_full, dq_full, &M[7][6]);
  calculate_C_7_6(q_full, dq_full, &C[7][6]);
  calculate_M_7_7(q_full, dq_full, &M[7][7]);
  calculate_C_7_7(q_full, dq_full, &C[7][7]);
  calculate_M_7_8(q_full, dq_full, &M[7][8]);
  calculate_C_7_8(q_full, dq_full, &C[7][8]);
  calculate_G_8(q_full, dq_full, &G[8]);
  calculate_M_8_0(q_full, dq_full, &M[8][0]);
  calculate_C_8_0(q_full, dq_full, &C[8][0]);
  calculate_M_8_1(q_full, dq_full, &M[8][1]);
  calculate_C_8_1(q_full, dq_full, &C[8][1]);
  calculate_M_8_2(q_full, dq_full, &M[8][2]);
  calculate_C_8_2(q_full, dq_full, &C[8][2]);
  calculate_M_8_3(q_full, dq_full, &M[8][3]);
  calculate_C_8_3(q_full, dq_full, &C[8][3]);
  calculate_M_8_4(q_full, dq_full, &M[8][4]);
  calculate_C_8_4(q_full, dq_full, &C[8][4]);
  calculate_M_8_5(q_full, dq_full, &M[8][5]);
  calculate_C_8_5(q_full, dq_full, &C[8][5]);
  calculate_M_8_6(q_full, dq_full, &M[8][6]);
  calculate_C_8_6(q_full, dq_full, &C[8][6]);
  calculate_M_8_7(q_full, dq_full, &M[8][7]);
  calculate_C_8_7(q_full, dq_full, &C[8][7]);
  calculate_M_8_8(q_full, dq_full, &M[8][8]);
  calculate_C_8_8(q_full, dq_full, &C[8][8]);
}
