import sympy as sp

# 1. Define Symbols
bx, by, bz = sp.symbols('bx by bz')
tx, ty, tz = sp.symbols('tx ty tz')

# 2. Define Helper Functions
def rot_x(theta):
    c = sp.cos(theta)
    s = sp.sin(theta)
    return sp.Matrix([
        [1, 0, 0],
        [0, c, -s],
        [0, s, c]
    ])

def rot_y(theta):
    c = sp.cos(theta)
    s = sp.sin(theta)
    return sp.Matrix([
        [c, 0, s],
        [0, 1, 0],
        [-s, 0, c]
    ])

def rot_z(theta):
    c = sp.cos(theta)
    s = sp.sin(theta)
    return sp.Matrix([
        [c, -s, 0],
        [s, c, 0],
        [0, 0, 1]
    ])

# 3. Construct Matrices (Order: Rx * Ry * Rz)
print("Building Symbolic Matrices...")

R_base_rot = rot_x(bx) * rot_y(by) * rot_z(bz)

# Base Rotation (With Hardcoded Gimbal Offset applied)
R_base = sp.Matrix([
    [-R_base_rot[0,0], -R_base_rot[0,1], -R_base_rot[0,2]],
    [ R_base_rot[2,0],  R_base_rot[2,1],  R_base_rot[2,2]],
    [ R_base_rot[1,0],  R_base_rot[1,1],  R_base_rot[1,2]]
])

R_tgt = rot_x(tx) * rot_y(ty) * rot_z(tz)

# 4. Compute Relative Rotation Matrix
R_loc = R_base.T * R_tgt

# --- FIX IS HERE: Use [row, col] for everything ---
elements_to_solve = [
    R_loc[0,0], R_loc[0,1], 
    R_loc[1,0], R_loc[1,1], 
    R_loc[2,0], R_loc[2,1]  # <--- This was the error
]

# 5. Generate Optimized C Code (CSE)
print("Optimizing Algebra (CSE)...")
replacements, calculated_elements = sp.cse(
    elements_to_solve,
    symbols=sp.numbered_symbols("tmp_")
)

r00, r01, r10, r11, r20, r21 = calculated_elements

# 6. Write the File
print("Writing inverse_position.c...")
with open("inverse_position.c", "w") as f:
    f.write('/* Auto-Generated by build_IK.py */\n')
    f.write('#include "inverse_position.h"\n')
    f.write('#include <math.h>\n')
    f.write('#include <stdio.h>\n\n')
    
    f.write('#ifndef M_PI\n#define M_PI 3.14159265358979323846\n#endif\n\n')
    f.write('#define DEG2RAD(x) ((x) * M_PI / 180.0)\n')
    f.write('#define RAD2DEG(x) ((x) * 180.0 / M_PI)\n\n')

    f.write('// J2 Axis Constants\n')
    f.write('static const double J2_uy = 0.2582889370066548;\n')
    f.write('static const double J2_uz = -0.966067712440475;\n')
    f.write('static const double K1 = 0.06671317498; // uy^2\n')
    f.write('static const double K2 = 0.93328682502; // uz^2\n\n')

    f.write('static double normalize_angle_deg(double angle) {\n')
    f.write('    while (angle > 180.0)  angle -= 360.0;\n')
    f.write('    while (angle < -180.0) angle += 360.0;\n')
    f.write('    return angle;\n')
    f.write('}\n\n')

    f.write('int inverse_position_kinematics(\n')
    f.write('    double theta_xb, double theta_yb, double theta_zb,\n')
    f.write('    double ee_roll, double ee_pitch, double ee_yaw,\n')
    f.write('    double *q1_deg, double *q2_deg, double *q3_deg)\n{\n')
    
    f.write('    // 1. Convert Inputs to Radians\n')
    f.write('    double bx = DEG2RAD(theta_xb);\n')
    f.write('    double by = DEG2RAD(theta_yb);\n')
    f.write('    double bz = DEG2RAD(theta_zb);\n')
    f.write('    double tx = DEG2RAD(ee_roll);\n')
    f.write('    double ty = DEG2RAD(ee_pitch);\n')
    f.write('    double tz = DEG2RAD(ee_yaw);\n\n')

    f.write('    // 2. Symbolic Computation of Relative Matrix Elements\n')
    
    for sym, expr in replacements:
        c_code = sp.printing.ccode(expr)
        f.write(f'    double {sym} = {c_code};\n')
    
    f.write('\n    // 3. Relevant Elements of R_loc = R_base^T * R_tgt\n')
    f.write(f'    double R00 = {sp.printing.ccode(r00)};\n')
    f.write(f'    double R01 = {sp.printing.ccode(r01)};\n')
    f.write(f'    double R10 = {sp.printing.ccode(r10)};\n')
    f.write(f'    double R11 = {sp.printing.ccode(r11)};\n')
    f.write(f'    double R20 = {sp.printing.ccode(r20)};\n')
    f.write(f'    double R21 = {sp.printing.ccode(r21)};\n\n')

    f.write('    // 4. Analytical Solver (Exact Geometric Decomposition)\n\n')

    f.write('    // --- Step A: Solve q2 ---\n')
    f.write('    // cos(q2) = (R11 - uy^2) / uz^2\n')
    f.write('    double val = (R11 - K1) / K2;\n')
    f.write('    if (val > 1.0) val = 1.0;\n')
    f.write('    if (val < -1.0) val = -1.0;\n')
    f.write('    double q2_rad = acos(val);\n')
    f.write('    *q2_deg = RAD2DEG(q2_rad);\n\n')

    f.write('    // --- Step B: Solve q1 ---\n')
    f.write('    double c2 = cos(q2_rad);\n')
    f.write('    double s2 = sin(q2_rad);\n')
    f.write('    double v_x = -J2_uz * s2;\n')
    f.write('    double v_z = J2_uy * J2_uz * (1.0 - c2);\n')
    f.write('    double w_x = R01;\n')
    f.write('    double w_z = R21;\n')
    f.write('    double q1_rad = atan2(w_x, w_z) - atan2(v_x, v_z);\n')
    f.write('    *q1_deg = normalize_angle_deg(RAD2DEG(q1_rad));\n\n')

    f.write('    // --- Step C: Solve q3 ---\n')
    f.write('    double c1 = cos(q1_rad);\n')
    f.write('    double s1 = sin(q1_rad);\n')
    f.write('    double t00 = c1 * R00 - s1 * R20;\n')
    f.write('    double t10 = R10;\n')
    f.write('    double t20 = s1 * R00 + c1 * R20;\n')
    f.write('    double rem00 = c2*t00 + (J2_uz*s2)*t10 - (J2_uy*s2)*t20;\n')
    f.write('    double r21_inv = J2_uz*J2_uy*(1.0-c2);\n')
    f.write('    double r22_inv = c2 + J2_uz*J2_uz*(1.0-c2);\n')
    f.write('    double rem20 = (J2_uy*s2)*t00 + r21_inv*t10 + r22_inv*t20;\n')
    f.write('    double q3_rad = atan2(-rem20, rem00);\n')
    f.write('    *q3_deg = normalize_angle_deg(RAD2DEG(q3_rad));\n\n')

    f.write('    return 0;\n}\n')

print("Done! Generated inverse_position.c")